enemies_list = [
    'Adoring Fan',
    'Ancient Dragon',
    'Ancient Vampire',
    'Apprentice Conjurer',
    'Apprentice Fire Mage',
    'Apprentice Ice Mage',
    'Apprentice Mage',
    'Apprentice Necromancer',
    'Apprentice Storm Mage',
    'Arch Conjurer',
    'Arch Cryomancer',
    'Arch Electromancer',
    'Arch Necromancer',
    'Arch Pyromancer',
    'Ascendant Conjurer',
    'Ascendant Necromancer',
    'Bandit',
    'Bandit Chief',
    'Bandit Highwayman',
    'Bandit Marauder',
    'Bandit Outlaw',
    'Bandit Plunderer',
    'Bandit Thug',
    'Bear',
    'Blood Dragon',
    'Boneman',
    'Cave Bear',
    'Chaurus',
    'Chaurus Hunter',
    'Chaurus Reaper',
    'Conjurer',
    'Cryomancer',
    'Dark Brotherhood Assassin',
    'Death Hound',
    'Deranged Khajiit',
    'Disgraced City Guard',
    'Dragon',
    'Dragon Priest',
    'Draugr',
    'Draugr Death Overlord',
    'Draugr Deathlord',
    'Draugr Overlord',
    'Draugr Scourge',
    'Draugr Scourge Lord',
    'Draugr Thrall',
    'Draugr Warrior',
    'Draugr Wight',
    'Draugr Wight Overlord',
    'Dremora Caitiff',
    'Dremora Churl',
    'Dremora Kynreeve',
    'Dremora Kynval',
    'Dremora Markynaz',
    'Dremora Valkynaz',
    'Elder Dragon',
    'Electromancer',
    'Falmer',
    'Falmer Gloomlurker',
    'Falmer Nightprowler',
    'Falmer Shadowmaster',
    'Falmer Skulker',
    'Falmer Warmonger',
    'Fire Mage',
    'Fire Wizard',
    'Flame Atronach',
    'Forsworn',
    'Forsworn Briarheart',
    'Forsworn Briarheart ',
    'Forsworn Forager',
    'Forsworn Looter',
    'Forsworn Pillager',
    'Forsworn Ravager',
    'Forsworn Warlord',
    'Frost Atronach',
    'Frost Dragon',
    'Frost Giant',
    'Frost Troll',
    'Frost Wizard',
    'Gargoyle',
    'Ghost',
    'Giant',
    'Giant Frostbite Spider',
    'Giant Mudcrab',
    'Hagraven',
    'Hulking Draugr',
    'Ice Mage',
    'Ice Wizard',
    'Ice Wolf',
    'Ice Wraith',
    'Imperial Gladiator',
    'Large Frostbite Spider',
    'Large Mudcrab',
    'Master Conjurer',
    'Master Necromancer',
    'Mudcrab',
    'Necro Mage',
    'Necromancer',
    'Pyromancer',
    'Renegade Imperial Soldier',
    'Renegade Storm Cloak',
    'Restless Draugr',
    'Sabre Cat',
    'Skeever',
    'Skeleton Warlock',
    'Skeleton Warlord',
    'Skeleton Warrior',
    'Small Frostbite Spider',
    'Snow Bear',
    'Snow-covered',
    'Snowy Sabre Cat',
    'Spriggan',
    'Spriggan Earth Mother',
    'Spriggan Matron',
    'Storm Atronach',
    'Storm Mage',
    'Storm Wizard',
    'Thalmor Justiciar',
    'Thief',
    'Troll',
    'Vampire',
    'Vampire Mistwalker',
    'Vampire Nightstalker',
    'Werewolf',
    'Wispmother',
    'Wolf',
    'Forsworn pillager',
    "It's a bear!",
    'deranged Khajiit',
    'bloodthirsty vampire',
    'skeleton warlock'
]
